language: julia
os:
    - linux
julia:
    - 0.6
    - 1.0
    - 1.1
notifications:
    email: false
after_success:
  - julia -e 'ENV["TRAVIS_JULIA_VERSION"] != "1.0" && ENV["TRAVIS_OS_NAME"] != "osx" && exit(); using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
